name: 'configmap-update'
description: 'configmap update action'
inputs:
  region:
    description: 'k8s kubeconfig'
    required: false
    default: '.kube/config'
  cluster-name:
    description: 'cluster name'
    required: true
    default: ''
  name:
    description: 'configmap name'
    required: true
    default: 'alerting-rules'
  namespace:
    description: 'namespace'
    required: true
    default: 'default'
  files:
    description: 'file paths'
    required: false
    default: ''
  data:
    description: 'configmap data'
    required: false
    default: '{}'
  dir:
    description: 'config path'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.files }}
    - ${{ inputs.data }}
    - ${{ inputs.region}}
    - ${{ inputs.cluster-name }}
