name: Self

on:
  push:
    branches:
      - main


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
#  build:
#    runs-on: self-hosted
#    steps:
#      - name: Set up Go 1.17
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.17
#        id: go
#
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Build
#        run: |
#          go mod tidy
#          go mod vendor
#          make build

  test:
    runs-on: self-hosted
#    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"
#      - uses: aws-actions/setup-sam@v1

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}

#      - id: install
#        uses: azure/setup-kubectl@v2.0

#      - name: Update Kubeconfig
#        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
#
#      - id: kubeconfig
#        name: Kubeconfig Params
#        run: |
#          cp -r ~/.kube ./
#          cat .kube/config

#      - name: User This Tag
#        run: sed -i "s/latest/${{ github.sha }}/g"  Dockerfile

      - name: Self
        uses: ./
        with:
#          kubeconfig: /github/workspace/.kube/config
          name: alerting-rules
          namespace: default
          dir: example
          region: ${{ secrets.AWS_REGION }}
          cluster-name: ${{ secrets.EKS_CLUSTER_NAME }}
#          files: |
#            - example/test.yml


